# Generated by Django 5.1.3 on 2024-12-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='existing_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
        migrations.AddField(
            model_name='user',
            name='exist',
            field=models.CharField(default=2, max_length=3),
            preserve_default=False,
        ),
    ]
