# Generated by Django 5.1.3 on 2024-12-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_user_existing_customer_remove_user_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
