# Generated by Django 5.1.3 on 2024-12-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='message',
            field=models.TextField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
